version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: '[github-actions] '
      prefix-development: '[github-actions] '
      include: scope

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '[maven] '
      prefix-development: '[maven] '
      include: scope
